// At what N does VectorMatrix.topKCosine beat a hand-written loop plus sort?
//
// Run with:
//   dart run bench/break_even.dart
//
// The baseline is the scan-and-sort in naive.dart, the same one
// bench/bench.dart quotes at 10,000 and 100,000 rows. This script sweeps
// row count across four orders of magnitude at a realistic embedding
// size so the README can show the crossover instead of only the large-N
// win. Dart VM only: dart2js and dart2wasm need a browser, and this
// harness does not launch one.

import 'dart:math';
import 'dart:typed_data';

import 'package:vector_kit/vector_kit.dart';

import 'naive.dart';

const dim = 768;
const k = 10;
const queryPool = 8;

// 10^1 through 10^5, with log-spaced points in between so the crossover
// is not hidden between two powers of ten.
const rowCounts = [10, 32, 100, 320, 1000, 3200, 10000, 32000, 100000];

void main() {
  print('topKCosine vs loop+sort, k=$k, $dim-d, Dart VM.');
  print(
    'Not measured: dart2js, dart2wasm '
    '(this harness does not launch a browser).\n',
  );
  print(
    '${'N'.padLeft(8)}  '
    '${'loop+sort'.padLeft(12)}  '
    '${'topKCosine'.padLeft(12)}  '
    '${'speedup'.padLeft(8)}  '
    'winner',
  );

  final rows = [for (final n in rowCounts) measure(n)];
  int? firstWin;
  for (final row in rows) {
    final winner = row.speedup > 1 ? 'topKCosine' : 'loop+sort';
    if (firstWin == null && row.speedup > 1) firstWin = row.n;
    print(
      '${row.n.toString().padLeft(8)}  '
      '${_us(row.naiveUs).padLeft(12)}  '
      '${_us(row.kitUs).padLeft(12)}  '
      '${row.speedup.toStringAsFixed(2).padLeft(7)}x  '
      '$winner'
      '${row.agreementNote}',
    );
  }

  print('');
  if (firstWin == null) {
    print(
      'VectorMatrix.topKCosine did not beat the loop+sort at any '
      'measured N (largest ${rowCounts.last}).',
    );
  } else if (firstWin == rowCounts.first) {
    print(
      'VectorMatrix.topKCosine was already faster at the smallest '
      'measured N ($firstWin). There is no runtime crossover in this '
      'sweep: the loop is slower at every size, and the reason to skip '
      'the package at small N is the dependency, not the clock.',
    );
  } else {
    print(
      'First measured N where VectorMatrix.topKCosine is faster: '
      '$firstWin.',
    );
  }

  // Markdown for the README. Regenerated by running this file.
  print('');
  print('| rows | loop + sort | topKCosine | vs the loop |');
  print('| ---: | ----------: | ---------: | ----------: |');
  for (final row in rows) {
    print(
      '| ${row.n} | ${_us(row.naiveUs)} | ${_us(row.kitUs)} | '
      '${row.speedup.toStringAsFixed(1)}x |',
    );
  }
}

({int n, double naiveUs, double kitUs, double speedup, String agreementNote})
measure(int rows) {
  final rng = Random(7);
  final matrix = VectorMatrix(dim);
  for (var r = 0; r < rows; r++) {
    matrix.add(
      Float32List.fromList([
        for (var i = 0; i < dim; i++) rng.nextDouble() * 2 - 1,
      ]),
    );
  }
  final queries = [
    for (var q = 0; q < queryPool; q++)
      Float32List.fromList([
        for (var i = 0; i < dim; i++) rng.nextDouble() * 2 - 1,
      ]),
  ];

  var agreement = 0;
  const checked = 3;
  for (final query in queries.take(checked)) {
    final naive = naiveTopKCosine(matrix, query, k);
    final kit = matrix.topKCosine(query, k);
    final n = min(k, naive.length);
    for (var i = 0; i < n; i++) {
      if (naive[i].$1 == kit[i].$1) agreement++;
    }
  }

  final repeats = _repeatsFor(rows);
  final trials = rows >= 10000 ? 3 : 5;

  // Warm both paths for as many calls as a timed trial, so the JIT is
  // not still compiling in the first sample.
  var sink = 0;
  for (var i = 0; i < repeats; i++) {
    final q = queries[i & (queryPool - 1)];
    sink += naiveTopKCosine(matrix, q, k).first.$1;
    sink += matrix.topKCosine(q, k).first.$1;
  }

  final naiveSamples = <double>[];
  final kitSamples = <double>[];
  for (var t = 0; t < trials; t++) {
    final naiveWatch = Stopwatch()..start();
    for (var i = 0; i < repeats; i++) {
      sink += naiveTopKCosine(matrix, queries[i & (queryPool - 1)], k).first.$1;
    }
    naiveWatch.stop();
    naiveSamples.add(naiveWatch.elapsedMicroseconds / repeats);

    final kitWatch = Stopwatch()..start();
    for (var i = 0; i < repeats; i++) {
      sink += matrix.topKCosine(queries[i & (queryPool - 1)], k).first.$1;
    }
    kitWatch.stop();
    kitSamples.add(kitWatch.elapsedMicroseconds / repeats);
  }

  // Minimum of the in-process trials, matching platform_cost_test.dart.
  final naiveUs = _min(naiveSamples);
  final kitUs = _min(kitSamples);
  // sink is read so the compiler cannot drop the timed loops.
  if (sink == -1) print('unreachable $sink');

  final expected = checked * min(k, rows);
  final agreementNote = agreement == expected
      ? ''
      : '  (rank agreement $agreement/$expected)';
  return (
    n: rows,
    naiveUs: naiveUs,
    kitUs: kitUs,
    speedup: naiveUs / kitUs,
    agreementNote: agreementNote,
  );
}

/// Enough repeats that even N=10 spends hundreds of milliseconds on each
/// path, without making N=100,000 run for minutes.
int _repeatsFor(int rows) {
  if (rows <= 10) return 8000;
  if (rows <= 32) return 4000;
  if (rows <= 100) return 2000;
  if (rows <= 320) return 800;
  if (rows <= 1000) return 400;
  if (rows <= 3200) return 80;
  if (rows <= 10000) return 40;
  if (rows <= 32000) return 20;
  return 12;
}

String _us(double us) {
  if (us >= 1000) return '${(us / 1000).toStringAsFixed(2)} ms';
  return '${us.toStringAsFixed(1)} µs';
}

double _min(List<double> samples) {
  var best = samples.first;
  for (final s in samples) {
    if (s < best) best = s;
  }
  return best;
}
